JaeGuipi/travelmaker

- styles/_mixins.scss
- styles/_reset.scss
- styles/_variables.scss
- styles/globals.scss
global Style 기본 설정하였습니다.
반응형 사이즈는 @include 하여 사용해 주시면 됩니다.
mobile / tablet / pc
```scss
@include mobile {
min-width: 375px;
}
```
폰트 사이즈는 rem 사용하기 편리하게 font-size: 62.5% 로 설정하였습니다.
추후 Next 로컬 폰트로 사용 시 글로벌 폰트는 삭제하도록 하겠습니다.
```scss
18px => 1.8rem
```
> Feat: global Style 기본 설정

- src/app/layout.tsx
- src/app/page.tsx
- src/hooks/useToast.ts
- [travelmaker #34](이슈 주소)
<br/>
- 프로젝트 전역에서 사용 가능한 토스트 구현
- 성공/실패/알림 토스트로 적절한 상태에 맞춰 사용 가능
```
import { useToast } from "@/hooks/useToast";
//컴포넌트 내부에 toast 불러오기
const { showSuccess, showError, notify } = useToast() ;
//토스트가 필요한 곳에서 사용
<button onClick={() => showSuccess("로그인 성공"}>성공 버튼</button>
```
<br/>
<br/>
- api 함수 만들기
<br/>
- 작업 하면서 추가로 필요한 토스트가 있다면 추가하도록 하겠습니다.
> feat(34): 성공/실패/알림 토스트 구현

- src/app/types/types.ts
- src/lib/api/user.ts
- [travalmaker #26 ]
<br/>
- user 함수 제작
- 타입 수정
```
//프로필 이미지 url 생성
export interface PostImage {
file: File;
}
export interface PostImageResponse {
profileImageUrl: string;
}
```
위와같이 리스폰스 타입을 재지정해주었고, 이미지 데이터는 File 타입으로 맞춰주었습니다.
<br/>
<br/>
- 커스텀fetch 함수를 통해 요청에 인증 보내기
<br/>
> Feat: API User 관련 함수 제작 #26

- src/app/types/notifications/notificationsTypes.ts
- src/app/types/types.ts
- src/lib/api/mynotifications.ts
- src/lib/api/myreservation.ts
- [#32]
- 내 알림 리스트 조회 API 추가하였습니다.
- 내 알림 삭제 API 추가하였습니다.
> Feat: MyNotifications API 추가

- src/actions/auth.action.ts
- src/app/(usercard)/layout.tsx
- src/app/(usercard)/my-info/page.tsx
- src/components/Auth/MyPageForm.module.scss
- src/components/Auth/MyPageForm.tsx
- src/components/Layout/Header/Header.module.scss
- src/components/Layout/Header/Header.tsx
- src/components/UserTab/UserTab.tsx
- src/middleware.ts
- src/styles/_variables.scss
- src/utils/customFetch.ts
- [#78]
- 공용 레이아웃 스타일 수정
- 유저 정보 Get api customFetch로 수정
- 미들웨어 리디렉션 주석처리
> Refactor: 유저 정보 customFetch로 수정 및 공용 레이아웃 스타일 변경

- src/components/MyReservationList/MyReservationList.tsx
- [travelmaker #76](이슈 주소)
<br/>
- dropdownItem 개별로 구현
- list로 만들어 수정
> fix(76): dropdown list로 수정

- next.config.mjs
- src/app/(usercard)/my-reservation/page.module.scss
- src/app/(usercard)/my-reservation/page.tsx
- src/components/ItemLayout/ItemLayout.module.scss
- src/components/ItemLayout/ItemLayout.tsx
- src/components/MyReservationItem/MyReservationItem.module.scss
- src/components/MyReservationItem/MyReservationItem.tsx
- src/components/MyReservationList/MyReservationList.module.scss
- src/components/MyReservationList/MyReservationList.tsx
- [travelmaker #76](이슈 주소)
<br/>
- 반응형 말줄임표 수정
- 불필요한 styling 삭제
- 금액 표시 수정 
- 리스트 없을 때 이미지 가운데 정렬 
<br/>
- 반응형 말줄임표  
- 리스트 없을 때 이미지 가운데 정렬  
<br/>
- 리뷰 모달 완성하러 가겠습니다.
<br/>
- 불필요한 코드 삭제한다고 했는데, 혹시 찾으신다면 알려주세요!
> fix(76): 반응형, 오타, 숫자 표기 수정

- src/app/(auth)/login/page.tsx
- src/app/(auth)/signup/page.tsx
- src/app/(usercard)/my-activities/[activityId]/page.tsx
- src/app/(usercard)/my-activities/page.tsx
- src/app/(usercard)/my-reservation/page.tsx
- src/app/(usercard)/reservation-status/page.tsx
- src/app/api/google-auth/route.ts
- src/app/api/kakao-auth/route.ts
- src/app/search-page/SearchResults.tsx
- src/app/search-page/page.tsx
- src/components/Activity/ActivityForm/ActivityForm.tsx
- src/components/Home/ActivityListSection/AllItemList.tsx
- src/components/Home/PopularSection/PopularItemList.tsx
- src/components/Input/CustomInput.tsx
- src/components/SearchBar.tsx
- src/lib/api/mynotifications.ts
- src/lib/api/myreservation.ts
- src/lib/api/user.ts
- src/types/activites/activitesTypes.ts
- 제목 : feat(issue 번호): 기능명
ex) feat(17): pull request template 작성
(확인 후 지워주세요)
- [레포 이름 #이슈번호](이슈 주소)
<br/>
- 기능에서 어떤 부분이
- 구현되었는지 설명해주세요
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
> hotfix: develop 브랜치 빌드 오류 해결

- src/app/api/google-auth/route.ts
- src/components/Activity/ActivityDetail/MapInfo.tsx
- 제목 : feat(issue 번호): 기능명
ex) feat(17): pull request template 작성
(확인 후 지워주세요)
- [레포 이름 #이슈번호](이슈 주소)
<br/>
- 기능에서 어떤 부분이
- 구현되었는지 설명해주세요
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
> hotfix: env 이름변경

- .gitignore
- src/app/api/google-auth/route.ts
- src/app/api/kakao-auth/route.ts
- src/components/Auth/SocialLoginAndSignup/SocialLoginAndSignup.tsx
- [travelmaker #140 (이슈 주소)
<br/>
- BASE_URL변수 추가하였습니다. 간편로그인 관련된 코드 이로인해 약간 수정하였습니다.
- 깃 이그노어 파일 수정하였습니다. 이제 깃허브는
```
.env
.env.development.local
.env.test.local
.env.production.local
.env.local
```
- 를 무시합니다. 이렇게 구분지은 이유는 노션에 서술해놓았습니다.
<br/>
<br/>
- 이그노어 파일이 깃허브에 한 번 올라간 다음 .env 파일들을 구분짓고, 수정해야 할 것 같아서 .env 작업은 머지가 되는대로 진행하겠습니다.
<br/>
> BASE_URL 등록 및 gitignore 파일 수정

- README.md
- src/components/BottomBar/BottomBar.module.scss
- src/components/BottomBar/BottomBar.tsx
- [travelmaker #139(이슈 주소)
<br/>
- 하단 바 경로 설정과 아이콘 변경
- readme 파일 생성
<br/>
<br/>
- 리팩토링
<br/>
- readme 파일은 처음 작성해서 부족한 부분이 많습니다. 미팅시간에 추가로 필요한 부분 논의하면 좋을 것 같아요!
> Refactor(139):  하단바링크연결등리팩토링리스트작업

- src/app/activities/[id]/page.tsx
- src/components/Activity/ActivityDetail/ActivityDetail.tsx
- src/components/Activity/ActivityDetail/MapInfo.tsx
- src/components/Activity/DetailSubImg.module.scss
- src/components/Activity/DetailSubImg.tsx
- src/components/Activity/Review/ReviewList.module.scss
- src/components/Activity/Review/ReviewList.tsx
- src/components/Activity/Schedules/Schedules.module.scss
- src/components/Activity/Schedules/Schedules.tsx
- src/components/Home/ActivityListSection/AllItemList.tsx
- src/components/Home/PopularSection/PopularItem.tsx
- src/components/Modal/ModalComponents/ConfirmModal.tsx
- [taskify #137 ]
- 코드 검토.....
- 
- 코드잇에서 리뷰리스트를 기본 3개로 불러와서 100개로 고정 넣엇습니닷..
> refactor : 체험 상세 페이지 

- src/app/(usercard)/my-reservation/ItemTitleLayout/ItemTitleLayout.tsx
- src/app/(usercard)/reservation-status/CalendarView.tsx
- src/app/(usercard)/reservation-status/page.module.scss
- src/app/(usercard)/reservation-status/page.tsx
- src/app/search-page/SearchResults.module.scss
- src/app/search-page/SearchResults.tsx
- src/app/search-page/page.tsx
- src/components/Input/CustomInput.tsx
- src/lib/auth.ts
- src/middleware.ts
- [travelmaker #145  ](이슈 주소)
<br/>
- 예약현황 페이지 UI 수정
- 검색 페이지 UI 수정
- .env 파일 구분
<br/>
<br/>
- 실시간 채팅 구현해보기
<br/>
> Chore(145): 예약현황 페이지 UI 추가 디자인 및 

- src/lib/api/activities.ts
> hotfix: 메인페이지 캐시데이터

- src/app/layout.tsx
- [travelmaker #159](이슈 주소)
<br/>
- 오픈 그래프 이미지 파일 이름 수정
> Chore(159) : image 파일 이름 언더바 -> 대시로 수정

- src/components/Home/ActivityListSection/ActivityList.module.scss
- src/components/Home/ActivityListSection/ActivityList.tsx
- src/components/Home/ActivityListSection/AllItemList.module.scss
- src/components/Home/ActivityListSection/CategoryList.module.scss
- src/components/Home/PopularSection/PopularItem.module.scss
- src/components/Home/PopularSection/PopularItemSwiper.module.scss
- 메인페이지 container 로 감싸져있어 mobile 에서 잘리는 현상이 수정했습니다!
> Design: 메인 페이지 css 수정

- src/components/Activity/DetailSubImg.module.scss
- src/components/Activity/Review/ReviewList.tsx
- src/components/Home/ActivityListSection/ActivityList.module.scss
- src/components/Home/PopularSection/PopularItemSwiper.module.scss
- src/components/Home/PopularSection/PopularItemSwiper.tsx
- src/components/Modal/ModalContainer.module.scss
> Design: 상세 모바일 별표, 주소영역

- src/app/layout.tsx
- src/components/Activity/ActivityDetail/ActivityDetail.module.scss
> Chore:og태그 수정

- src/actions/myReservation.ts
- src/app/(usercard)/my-reservation/page.tsx
- 리뷰 등록 후 상태 변경이 되지 않는 이슈로 revalidateTag 추가
> Fix: 리뷰 등록 후 상태 변경이 되지 않는 이슈

- src/actions/myReservation.ts
- src/app/(usercard)/my-reservation/MyReservationList/MyReservationList.tsx
- src/app/(usercard)/my-reservation/MyReservationList/ReviewContent.tsx
- src/app/(usercard)/my-reservation/page.tsx
> Fix: 리뷰 모달 수정

- src/components/Activity/Schedules/ScheduleDetail/components/Calendar.module.scss
- src/components/Activity/Schedules/ScheduleDetail/components/Calendar.tsx
> Feat: 지난 날짜 블러처리

- src/components/Home/VisualSection/MainSwiper.tsx
> LCP update

- package-lock.json
- package.json
- src/components/Home/VisualSection/MainSwiper.module.scss
- src/components/Home/VisualSection/MainSwiper.tsx
> Chore: LCP 개선
